#include <stdio.h>
#include <sys/types.h>
#include <dirent.h>
#include <errno.h>
#include <string.h>
#include <stdlib.h>
#include <limits.h>
#include <sys/stat.h>
#include <unistd.h>
#include <time.h>

#define YEeeeEt "--S"
#define YEEeEt "/"
#define YEEEt strlen
#define YEEeeet "--april"
#define YeeeeeEt res
#define YeeeeT [
#define YEEEEeT "--novembar"
#define YeEeeEt time->tm_mon
#define YEEEET stats
#define YeeeEt ]
#define YEeeEt -1
#define YeEEeet void
#define YeEeEEt time->tm_min
#define YeeeEEt time
#define YeeeEet strerror
#define YEEEet childResolvedPath
#define YeeEeT printf
#define YeeEEET <=
#define YeeeeeT err
#define YEEEEt stat
#define YEeEEEt "--mart"
#define YeEeEET free
#define YeEeeT namelist
#define YeEEET scandir
#define YEET const
#define YeEeET opts.sort
#define YEeEt i
#define YEEeEeT "--jul"
#define YeeET if
#define YEeeeet else
#define YeEEeET char**
#define YeEEEt n
#define YeEEet compare
#define YeEt year
#define Yeeet dirent*
#define YeEEEET "--sort"
#define Yeet char*
#define YeeEeEt !=
#define YEeeeT &filter
#define YeET month
#define YEeeet &namelist
#define YeEEEeT '-'
#define YeeeEET localtime
#define YeEEeeT parseOptions
#define YEEEeT realpath
#define YEEET i++
#define YEEeeeT "--maj"
#define YeEeeeT opts.month
#define yEet {
#define YEEEEEt 10
#define YeeeT dir
#define YEet }
#define Yeeeeeet 11
#define YeEeEet time->tm_mday
#define YeEeEeT time->tm_hour
#define YEeeEEt malloc
#define YeEeT ==
#define YEEeEET "--avgust"
#define yeEt struct
#define YEeEeEt "--p"
#define YEeeeeT strncmp
#define YeeeEeT tm*
#define YEeEEet "--januar"
#define YEeEeet sizeof
#define YeeEeet &stats.st_ctime
#define Yeeeeet &stats
#define YEEeET ->d_name
#define YEEt (
#define YeeEt )
#define YEeEeeT strncpy
#define YEeeEET *
#define YeeEEeT +
#define YeEEt NULL
#define YEeEet "scandir"
#define YeEeet dirent**
#define YeeEET ,
#define YEeeEeT buff
#define YEeeEet -
#define YEEEeET "--oktobar"
#define YEEEeeT "--septembar"
#define YeEEEEt strcmp
#define Yeeeet dir->d_name
#define YeEet opts.filter
#define YEEet 0
#define YEeet 1
#define YEeEEET 2
#define YeeeeEt errno
#define YEeeeET 3
#define YEEeeEt 4
#define YeeEeeT opts.year
#define YEEeEet 5
#define YEEeEEt 6
#define YEEeet strcpy
#define YeeEEt "%s:\n"
#define YEEEeet 7
#define YeeEeET &&
#define YEeEET 256
#define YEEEeEt 8
#define YeeEEet 1900
#define YeeeeET "%s\n"
#define YEEEEet 9
#define YeeeET list
#define YEeEeT char
#define YEeeET perror
#define YeEEeEt argc
#define YEEeeT strcat
#define yEET ;
#define YeEeeet continue
#define YEEeT <
#define YEeET =
#define yEEt sort
#define YeEeEt *compare
#define YeEeeET "  %d-%02d-%02d %02d:%02d %s\n"
#define YeEEeT alphasort
#define YEeEEt childPath
#define YeeEEEt time->tm_year
#define YEEeeET "--jun"
#define YEeEEeT "--februar"
#define YeeEet path
#define YEeeT for
#define YeEET return
#define yeET options
#define YeEEEet argv
#define YeeT filter
#define YeeeeeeT main
#define YEeT opts
#define yeeT typedef
#define yEeT int
#define YEeEeET atoi
#define YEEEEET "--decembar"
