#include <stdio.h>
#include <stdlib.h>
#include <limits.h>

#define YEEeEt 200
#define YeEeet i--
#define Yeeeet [
#define YEeeEt 'T'
#define YeeeeT ]
#define YEeEEt >>=
#define YEEEeT printf
#define YeeeT <=
#define Yeeeeet free
#define YEeeet 'y'
#define YEeEet 'E'
#define YeeEeT i
#define YEEEet generate_yeet
#define YeEeET if
#define YEeeeT else
#define yEEt n
#define YeeT n++
#define YEeEt char*
#define YEEeET i++
#define YeeEt INT_MAX
#define YeeeET capital
#define Yeet {
#define YEeet }
#define yEet unsigned
#define YeEET yeet_size++
#define YEEEEt "%-3d [%s]\n"
#define YEeET malloc
#define YeEEet ==
#define YEeT 16
#define YEEt yeet_size
#define YeEeeT %
#define YEEet sizeof
#define YEeeET 't'
#define YEeeT *yeet
#define yeET (
#define yEET )
#define YEEET yeet
#define YEEeT *
#define YEEEt +
#define YEEEET ,
#define YeeEEt -
#define YEeEeT 'e'
#define YeeEET 0
#define YeEEt 1
#define YeEeEt 2
#define YEET 4
#define YeeET &&
#define YeEEEt 'Y'
#define YeEEET :
#define yeeT char
#define YeEt ;
#define YEEeeT <
#define YEet =
#define YeEet >=
#define YeEEeT ?
#define YeET bit
#define YeeeEt '\0'
#define YeEeT <<=
#define YEeEET return
#define YeeEet for
#define YEEeet main
#define yEeT int
#define yeEt *generate_yeet
#define Yeeet while
